### ISSUE TITLE
Hyper Reservoirs deletes stored material

### ISSUE THREAD

**Issue by TroublesomeCorvid** [as-limc/oni-mods#2]
Right now, I'm using Fumihiko's Custom Buildings mod (https://steamcommunity.com/sharedfiles/filedetails/?id=1818138009), which changes the base storage capacity of reservoirs (among other things).

Unless I'm mistaken, your mod takes this base figure and multiplies it, correct?  Well, I noticed that if the amount of that product exceeds 100t, then the reservoir will continue to take in materials, but the amount in storage will not increase above 100t, effectively deleting whatever goes in there once 100t is reached.

I recommend that rather than use a multiplier, you instead use a user-inputted amount with a hard limit at 100t to prevent this from happening.

**Comment by as-limc** [comment]
Thank you for your information!
I'll see what I can do to optimize this. :)
