### ISSUE TITLE
laser turret not working after recent update

### ISSUE THREAD

**Issue by martijn805** [as-limc/oni-mods#4]
Hi, after the update today the steam laser turret mod does not work anymore.
Could you please take a look?

Thanks!

**Comment by martijn805** [comment]
I had a look myself and I was able to get it working again by changing:
[EventRef] private string _rotateSound = "AutoMiner_rotate";
into
private string _rotateSound = "AutoMiner_rotate";

I also had to comment out:
using FMODUnity;
But that may be a dependency issue on my end. Only started working with the tooling yesterday.

**Comment by as-limc** [comment]
Thank you for your effort! 
I've been playing other games for several months, and not taking care of these mods for a long time, since there's no big updates for ONI anyway. I'll look into this right now! :)

**Comment by as-limc** [comment]
It's caused by FMOD.
I've rebuilt the mod and publish an update, you may check it out in the workshop.

**Comment by martijn805** [comment]
Hi,

Awesome, thanks for updating it!

With regards,

Martijn
